# Generated by Django 5.0.4 on 2024-04-19 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_company_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 20, 56, 43, 518673, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='insuranceclient',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
