# Generated by Django 5.0.4 on 2024-04-20 11:58

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_company_app', '0003_insuranceclient_user_alter_basemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecontract',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insurance_company_app.insuranceagent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancecontract',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insurance_company_app.insuranceclient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancetype',
            name='percentage',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 11, 58, 8, 24924, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='insuranceagent',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
