# Generated by Django 5.0.4 on 2024-04-20 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_company_app', '0006_alter_basemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='created_at_withTZ',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 13, 47, 24, 452392, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='updated_at_withTZ',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 13, 47, 24, 452392, tzinfo=datetime.timezone.utc)),
        ),
    ]
