# Generated by Django 5.0.4 on 2024-04-20 20:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_company_app', '0008_alter_basemodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insurance_company_app.basemodel')),
                ('name', models.CharField(max_length=80)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField()),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
            bases=('insurance_company_app.basemodel',),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 20, 52, 3, 953312, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='created_at_withTZ',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 20, 52, 3, 953312, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insurance_company_app.basemodel')),
                ('text', models.TextField()),
                ('rating', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_company_app.insuranceclient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('insurance_company_app.basemodel',),
        ),
    ]
