# Generated by Django 5.0.4 on 2024-04-21 10:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_company_app', '0009_promocode_alter_basemodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonInfoAboutCompany',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insurance_company_app.basemodel')),
                ('logo', models.ImageField(upload_to='images/logo')),
                ('video', models.FileField(upload_to='videos/about_company')),
                ('history', models.TextField()),
                ('requestions', models.TextField()),
            ],
            options={
                'verbose_name': 'Информация о компании',
            },
            bases=('insurance_company_app.basemodel',),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insurance_company_app.basemodel')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('added_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
            bases=('insurance_company_app.basemodel',),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insurance_company_app.basemodel')),
                ('position_name', models.CharField(max_length=200)),
                ('salary', models.DecimalField(decimal_places=5, max_digits=10)),
                ('vacancy_description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
            bases=('insurance_company_app.basemodel',),
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 10, 2, 17, 335496, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='created_at_withTZ',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 10, 2, 17, 335496, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insurance_company_app.basemodel')),
                ('employee_image', models.ImageField(upload_to='')),
                ('position', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_company_app.insuranceagent')),
            ],
            options={
                'verbose_name_plural': 'Контакты',
            },
            bases=('insurance_company_app.basemodel',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insurance_company_app.basemodel')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images/news')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='insurance_company_app.insuranceagent')),
            ],
            options={
                'verbose_name_plural': 'Новости',
            },
            bases=('insurance_company_app.basemodel',),
        ),
    ]
