# Generated by Django 5.0.4 on 2024-04-21 11:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_company_app', '0010_commoninfoaboutcompany_faq_vacancy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commoninfoaboutcompany',
            options={'verbose_name_plural': 'Информация о компании'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='insurance_company_app.companybranch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 11, 19, 2, 527697, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='created_at_withTZ',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 11, 19, 2, 527697, tzinfo=datetime.timezone.utc)),
        ),
    ]
