# Generated by Django 5.0.4 on 2024-04-21 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_company_app', '0011_alter_commoninfoaboutcompany_options_vacancy_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceagent',
            name='job_position',
            field=models.CharField(default='Junior BelGosTrach Insurance Agent', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 12, 41, 30, 491874, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='created_at_withTZ',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 12, 41, 30, 491874, tzinfo=datetime.timezone.utc)),
        ),
    ]
