# Generated by Django 5.0.4 on 2024-04-22 17:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_company_app', '0012_insuranceagent_job_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecontract',
            name='insurance_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance_company_app.insuranceobject'),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 17, 30, 14, 749268, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='created_at_withTZ',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 17, 30, 14, 749268, tzinfo=datetime.timezone.utc)),
        ),
    ]
