# Generated by Django 5.0.4 on 2024-05-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_company_app', '0014_insuranceagent_photo_alter_basemodel_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basemodel',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='created_at_withTZ',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
