# Generated by Django 5.0.4 on 2024-05-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_company_app', '0015_rename_updated_at_basemodel_modified_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basemodel',
            old_name='updated_at_withTZ',
            new_name='modified_at_withTZ',
        ),
    ]
