# Generated by Django 5.0.4 on 2024-05-09 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_company_app', '0016_rename_updated_at_withtz_basemodel_modified_at_withtz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancetype',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='insurancetype',
            name='percentage',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
