# Generated by Django 5.0.4 on 2024-09-16 08:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_company_app', '0017_alter_insurancetype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceobject',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insurance_company_app.insuranceclient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='insurancetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='insurancetype',
            name='percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(error_messages='Rate must be in range 0-10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
